#!/bin/bash
# Usage : ./rename-host.sh
set -e
read macaddr < /sys/class/net/wlan0/address
macaddr=${macaddr//:}
macaddr=${macaddr:6}
echo "Renaming host to esieabot-$macaddr..."
hostnamectl set-hostname "esieabot-$macaddr"
sed -e '/127\.0\.1\.1/d' -i /etc/hosts
echo "127.0.1.1 esieabot-$macaddr" >> /etc/hosts
password=`head -c 10 /dev/random | md5sum | head -c 12`
nmcli con modify Hotspot wifi.ssid esieabot-$macaddr
nmcli con modify Hotspot wifi-sec.psk $password
systemctl restart NetworkManager
echo -e "SSID: esieabot-$macaddr\nKey: $password\n\nDo not edit this file, it won't have any effect." > /boot/esieabot/info/hotspot.txt
echo "Done, might need a reboot."

