#!/bin/bash
# Usage : ./reset-pi-passwd.sh
# Reset password of user "pi"
set -e
PASS=`head -c 10 /dev/random | md5sum | head -c 12`
echo -e "$PASS\n$PASS" | passwd pi
echo -e "User: pi\nPassword: $PASS\n\nDo not edit this file, it won't have any effect." > /boot/esieabot/info/pi.txt
