#!/bin/bash
# Usage : ./reset-samba-passwd.sh
# Reset samba password of user "pi"
set -e
SMBPASS=`head -c 10 /dev/random | md5sum | head -c 12`
echo -ne "$SMBPASS\n$SMBPASS\n" | smbpasswd -a -s pi
echo -e "User: pi\nPassword: $SMBPASS\n\nDo not edit this file, it won't have any effect." > /boot/esieabot/info/samba.txt
systemctl restart smbd
